#!/usr/bin/python3

num= int(input("what's the tempreature: "))

fc = int(input("press 1 if celsius or 2 if fahrenheit:"))

if fc == 1:
  F = ( num*1.8 +32)
  print ("your Temp is:{} Degree Fahrenheit".format(F))
elif fc == 2:
  C = (num -32)*.5556
  print ("your Temp is: {} Degree Fahrenheit ".format(C))
else:
    print ("please input a valid option")
   


  
  
  
(WHILE LOOP )
  #!/usr/bin/python3


count = 0 

while count < 10: 
    count += 1
    print("the count is :{}".format(count)) 
    if count == 5:
        print ("Count is 5")
        break

(FOR LOOP)

#!/usr/bin/python3

mylist = list(range(20))

newlist=[]

for num in mylist:
    print(num*3)
    newlist.append(num*3)

for x in newlist:
    print(x/3)
